### ISSUE TITLE
Greenboot failed to rollback when new commit fails in health check

### ISSUE THREAD

**Issue by yih-redhat** [fedora-iot/greenboot#105]
Issue description:
Provision a vm and boot, then upgrade to a new commit (which is a fake commit just for test and health check never pass). After reboot, greenboot health check fails and reboot several times, then finally fall back to previous commit. 
The problem is, when run rpm-ostree status, the new failed commit is still on top of old commit, like this:

[admin@vm-1 ~]$ rpm-ostree status
State: idle
Deployments:
  rhel-edge:centos/9/x86_64/edge
                  Version: 9-stream (2023-06-12T11:25:33Z)
               BaseCommit: de8c63c4444fdc53e8b927357f458250bdaaec938e24f2923fbc071ce7aa24c2
                     Diff: 1 added
            LocalPackages: greenboot-failing-unit-1.0-1.el8.noarch
● rhel-edge:centos/9/x86_64/edge
                  Version: 9-stream (2023-06-12T11:25:33Z)
                   Commit: de8c63c4444fdc53e8b927357f458250bdaaec938e24f2923fbc071ce7aa24c2

Actual result:
The rpm-ostree status order is not reversed, each reboot will try to boot with the top one

Expected result:
The rpm-ostree status order should be reversed

**Comment by say-paul** [comment]
Notes from discussion with systemd folks:
Greenboot Systemd:

- Remove general local-fs.target as its very generic and is best avoided an inturn include more specific files that requires dependency.
Example: RequiresMountsFor /dir

- Add OnFailure=greenboot-rollback.service as this will trigger when greenboot health check fails , though there should be a additional conditions in greenboot-rollback.service 

- Greenboot-rollback checks if boot_counter is set and equals to Zero.Though it still does not know if it should rollback or not as it needs to happen only till 1st successful reboot.One way is to add an additional script to put a stub somewhere which should trigger on ostree-finalize-staged and greenboot health check can remove it.

- Trying to avoid using DefaultDependencies=no but with using system-update-done we can include that as the service itself has the flag sets

- (May not be EDGE specific)- We can require mount for remote file systems.

- Look for use of systemd generators

- Greenboot is Requiredby=boot-complete.target which remains unchanged.

**Comment by say-paul** [comment]
fix is in :  #100

**Comment by say-paul** [comment]
@yih-redhat fixed in the above PR, you can retest it.
