### ISSUE TITLE
Add CI/CD pipeline

### ISSUE THREAD

**Issue by LorbusChris** [fedora-iot/greenboot#11]
The master branch is already hooked up to copr [here](https://copr.fedorainfracloud.org/coprs/lorbus/greenboot/) and the dev branch [here](https://copr.fedorainfracloud.org/coprs/lorbus/greenboot-dev/).

I'd like a more elaborate pipeline that runs all test cases (currently just green and red states), possibly on multiple platforms.

**Comment by jnogol** [comment]
Working on this. I'm using [bats-core](https://github.com/bats-core/bats-core) for the unit testing and will use [GitHub Actions](https://github.com/features/actions) for ensuring it's run on pull requests.
