### ISSUE TITLE
for simplified greenboot, greenboot-rollback service cannot be enabled

### ISSUE THREAD

**Issue by yih-redhat** [fedora-iot/greenboot#110]
Two issues for greenboot-rollback service:

1.When enable greenboot-rollback.service, it failed and reported error.
2.Check the log of greenboot-rollback.service for first boot, there is an error message "Error: Rollback not initiated as boot_counter is either unset or not equal to 0"

[admin@vm-1 ~]$ systemctl enable --now greenboot-rollback.service
Job for greenboot-rollback.service failed because the control process exited with error code.
See "systemctl status greenboot-rollback.service" and "journalctl -xeu greenboot-rollback.service" for details.

[admin@vm-1 ~]$ journalctl -b -5 -u greenboot-rollback.service
Jul 19 09:49:48 vm-1 systemd[1]: Starting Greenboot rollback...
Jul 19 09:49:48 vm-1 greenboot[1747]: Error: Rollback not initiated as boot_counter is either unset or not equal to 0
Jul 19 09:49:48 vm-1 systemd[1]: greenboot-rollback.service: Main process exited, code=exited, status=1/FAILURE
Jul 19 09:49:48 vm-1 systemd[1]: greenboot-rollback.service: Failed with result 'exit-code'.
Jul 19 09:49:48 vm-1 systemd[1]: Failed to start Greenboot rollback.

**Comment by LorbusChris** [comment]
What's the reason you're invoking greenboot-rollback.service manually? It's not intended to be used that way.
Maybe you're looking for `rpm-ostree rollback`?

**Comment by yih-redhat** [comment]
sorry I didn't make it clear, it's for simplified greenboot. currently the greenboot* services are not enabled by default, and @say-paul asked me to enable them manually.

**Comment by say-paul** [comment]
@yih-redhat  `--now` starts the service immediately which is why the it reported failure as there is no counter set, which is expected.

**Comment by say-paul** [comment]
@yih-redhat  I have fixed this to not returning the error any more as its just a log it as an info.

**Comment by yih-redhat** [comment]
fixed, closing this bug.
