### ISSUE TITLE
RFE: Support for systemd-boot

### ISSUE THREAD

**Issue by pm4rcin** [fedora-iot/greenboot#115]
Hi, from my understanding since F39 users will be able to [install systemd-boot cleanly](https://fedoraproject.org/wiki/Changes/cleanup_systemd_install) even on Fedora-iot which raises the question if greenboot is going to work with it or will have to be disabled on such installs?

**Comment by say-paul** [comment]
Greenboot currently depends on grub variable, so It wont work for systemd-boot. I am not sure even ostree supports that too, Need some level of more investigation.

**Comment by LorbusChris** [comment]
That's indeed not supported yet by OSTree, see https://github.com/ostreedev/ostree/issues/1719
Once that's unblocked, it'll also require some additional support in greenboot itself, as sd-boot uses a different (better) mechanism for boot counting (see: https://uapi-group.org/specifications/specs/boot_loader_specification/#boot-counting)

**Comment by cgwalters** [comment]
It makes sense, but honestly I think android-boot integration is more important (in progress for ostree).  (And after that, supporting zipl)

**Comment by pm4rcin** [comment]
I'm not really sure if it's truly needed since there's effort on UKIs and just not using bootloader at all so I'll close but feel free to reopen if you think it's worth the effort.

**Comment by bam80** [comment]
Fedora Silverblue can boot with sd-boot installed, but IoT apparently not - it fallbacks to emergency mode without commandline, as root account is locked.

Any idea why it's happening?
