### ISSUE TITLE
provide mechanism for disabling certain default health checks

### ISSUE THREAD

**Issue by miabbott** [fedora-iot/greenboot#119]
The opinion around #117 is that removal of the health checks is too coarse and severely limits the usefulness of `greenboot` as a whole.

Instead, let's investigate a means of enabling/disabling the default health checks.

**Comment by 7flying** [comment]
- we need to give the user the ability to choose whether they want the default health checks enabled or not (all of them, some of them etc), given that they may have the default-health-checks RPM installed
