### ISSUE TITLE
with latest greenboot, monitor services create a cycle

### ISSUE THREAD

**Issue by runcom** [fedora-iot/greenboot#76]
stdout: |-
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Found ordering cycle on greenboot-grub2-set-success.service/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Found dependency on boot-complete.target/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Found dependency on greenboot-service-monitor.service/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Found dependency on multi-user.target/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Job greenboot-grub2-set-success.service/start deleted to break ordering cycle starting with multi-user.target/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Found ordering cycle on greenboot-status.service/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Found dependency on greenboot-task-runner.service/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Found dependency on boot-complete.target/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Found dependency on greenboot-service-monitor.service/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Found dependency on multi-user.target/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Job greenboot-status.service/start deleted to break ordering cycle starting with multi-user.target/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Found ordering cycle on greenboot-task-runner.service/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Found dependency on boot-complete.target/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Found dependency on greenboot-service-monitor.service/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Found dependency on multi-user.target/start
    Aug 27 04:39:54 localhost systemd[1]: multi-user.target: Job greenboot-task-runner.service/start deleted to break ordering cycle starting with multi-user.target/start

full logs at https://github.com/virt-s1/rhel-edge/runs/8047704187?check_suite_focus=true#step:4:5342 - bz https://bugzilla.redhat.com/show_bug.cgi?id=2120593#c1

**Comment by runcom** [comment]
my suspictions are #70 and #72

**Comment by runcom** [comment]
@LorbusChris ptal

**Comment by miabbott** [comment]
Is this closed with https://github.com/fedora-iot/greenboot/pull/78?
