### ISSUE TITLE
Should all the greenboot-* systemd services be enabled?

### ISSUE THREAD

**Issue by alcir** [fedora-iot/greenboot#91]
https://github.com/fedora-iot/greenboot/blob/650ce7724b5394c5a50c8428dd193260e3127870/README.md?plain=1#L36

Do `greenboot-rpm-ostree-grub2-check-fallback greenboot-grub2-set-counter redboot-task-runner redboot-auto-reboot` should be enabled as well?

**Comment by 7flying** [comment]
No, those are only triggered when a heath check fails and handle the reboot/rollback of your system.

**Comment by alcir** [comment]
mmm, are you sure? Because if I leave them disabled (I was performing some test on Fedora Silverblue), greenboot doesn't work as described.
In addition, on Fedora IoT (if I'm not wrong) these services seem to be enabled.

**Comment by nullr0ute** [comment]
> mmm, are you sure? Because if I leave them disabled (I was performing some test on Fedora Silverblue), greenboot doesn't work as described. In addition, on Fedora IoT (if I'm not wrong) these services seem to be enabled.

Because IoT enables them in the IoT presets: /usr/lib/systemd/system-preset/80-iot.preset

**Comment by alcir** [comment]
> Because IoT enables them in the IoT presets: /usr/lib/systemd/system-preset/80-iot.preset

So in a system without such presets, they should be manually enabled?

**Comment by nullr0ute** [comment]
> > Because IoT enables them in the IoT presets: /usr/lib/systemd/system-preset/80-iot.preset
> 
> So in a system without such presets, they should be manually enabled?

Not all, just the ones specified in the presets.

**Comment by alcir** [comment]
Yes.
Looking at `/usr/lib/systemd/system-preset/80-iot.preset`, what I mean in this issue is: in the readme, in addition to `greenboot-task-runner greenboot-healthcheck greenboot-status greenboot-loading-message` also `greenboot-rpm-ostree-grub2-check-fallback greenboot-grub2-set-counter redboot-task-runner redboot-auto-reboot` should be added. Isn't it?

**Comment by LorbusChris** [comment]
@alcir all the greenboot-* services present in `80-iot.preset` should be added to the README for completeness. Feel free to open a PR.

It does looks like `greenboot-loading-message.service` is not currently enabled in [the preset file](https://src.fedoraproject.org/rpms/fedora-release/blob/rawhide/f/80-iot.preset). I'm not sure whether that's intended or an oversight, in which case it should probably be added to the preset.

**Comment by alcir** [comment]
> It does looks like `greenboot-loading-message.service` is not currently enabled in [the preset file](https://src.fedoraproject.org/rpms/fedora-release/blob/rawhide/f/80-iot.preset). I'm not sure whether that's intended or an oversight, in which case it should probably be added to the preset.

https://src.fedoraproject.org/rpms/fedora-release/pull-request/245

Thank you all.
